<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Compl_m_nt_tat_civil',
        'title' => E::ts('Complémént état civil'),
        'collapse_display' => TRUE,
        'weight' => 6,
        'created_date' => '2022-04-16 07:37:18',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Compl_m_nt_tat_civil_Civilit_user',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Compl_m_nt_tat_civil_Civilit_user',
        'title' => E::ts('Complémént état civil :: Civilité user'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Compl_m_nt_tat_civil_Civilit_user_OptionValue_Mr_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Compl_m_nt_tat_civil_Civilit_user',
        'label' => E::ts('M.'),
        'value' => '1',
        'name' => 'Mr_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Compl_m_nt_tat_civil_Civilit_user_OptionValue_Mme_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Compl_m_nt_tat_civil_Civilit_user',
        'label' => E::ts('Mme.'),
        'value' => '2',
        'name' => 'Mme_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Compl_m_nt_tat_civil_Civilit_user_OptionValue_Mlle_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Compl_m_nt_tat_civil_Civilit_user',
        'label' => E::ts('Mlle.'),
        'value' => '3',
        'name' => 'Mlle_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Compl_m_nt_tat_civil_Civilit_user_OptionValue_Mx',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Compl_m_nt_tat_civil_Civilit_user',
        'label' => E::ts('Mx.'),
        'value' => '4',
        'name' => 'Mx',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil_CustomField_Civilit_user',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Compl_m_nt_tat_civil',
        'name' => 'Civilit_user',
        'label' => E::ts('Civilité user'),
        'html_type' => 'Select',
        'is_required' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'civilit_user_197',
        'option_group_id.name' => 'Compl_m_nt_tat_civil_Civilit_user',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil_CustomField_ad_ok',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Compl_m_nt_tat_civil',
        'name' => 'ad_ok',
        'label' => E::ts('ad_ok'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_active' => FALSE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ad_ok_28',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil_CustomField_Ville_de_naissance',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Compl_m_nt_tat_civil',
        'name' => 'Ville_de_naissance',
        'label' => E::ts('Ville de naissance'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ville_de_naissance_47',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil_CustomField_Ann_e_naissance',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Compl_m_nt_tat_civil',
        'name' => 'Ann_e_naissance',
        'label' => E::ts('Année naissance (auto)'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'help_post' => E::ts('Valeur calculée lors de la purge des données pour conserver seulement année de décès'),
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ann_e_naissance_auto__148',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil_CustomField_Adresse_incorrecte',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Compl_m_nt_tat_civil',
        'name' => 'Adresse_incorrecte',
        'label' => E::ts('Adresse incorrecte'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '0',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'adresse_incorrecte_66',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil_CustomField_Heure_du_d_c_s',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Compl_m_nt_tat_civil',
        'name' => 'Heure_du_d_c_s',
        'label' => E::ts('Heure du décès'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'help_pre' => E::ts('hh:mm'),
        'text_length' => 255,
        'time_format' => 2,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'heure_du_d_c_s_152',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Compl_m_nt_tat_civil_CustomField_Ann_e_de_d_c_s_auto_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Compl_m_nt_tat_civil',
        'name' => 'Ann_e_de_d_c_s_auto_',
        'label' => E::ts('Année de décès (auto)'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'help_post' => E::ts('Année de décès calculée automatiquement au moment de la purge'),
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ann_e_de_d_c_s_auto__186',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
