<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Transfert_vers_autre_centre',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Transfert_vers_autre_centre',
        'title' => E::ts('Transfert vers autre centre'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Donateur'],
        'collapse_display' => TRUE,
        'help_pre' => E::ts('<p>R&eacute;orientation du corps vers un autre centre de don</p>'),
        'weight' => 11,
        'collapse_adv_display' => TRUE,
        'created_date' => '2023-04-29 08:49:49',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'centre_de_don_20210419175120',
        'title' => E::ts('Centre de don'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Amiens',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Amiens'),
        'value' => '4',
        'name' => 'Amiens',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Angers',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Angers'),
        'value' => '14',
        'name' => 'Angers',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Besan_on',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Besançon'),
        'value' => '9',
        'name' => 'Besan_on',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Bordeaux',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Bordeaux'),
        'value' => '46',
        'name' => 'Bordeaux',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Brest',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Brest'),
        'value' => '8',
        'name' => 'Brest',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Caen',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Caen'),
        'value' => '3',
        'name' => 'Caen',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Clermont_Ferrand',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Clermont-Ferrand'),
        'value' => '18',
        'name' => 'Clermont_Ferrand',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Dijon',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Dijon'),
        'value' => '11',
        'name' => 'Dijon',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Grenoble',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Grenoble'),
        'value' => '41',
        'name' => 'Grenoble',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Lille',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Lille'),
        'value' => '5',
        'name' => 'Lille',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Limoges',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Limoges'),
        'value' => '16',
        'name' => 'Limoges',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Lyon',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Lyon'),
        'value' => '19',
        'name' => 'Lyon',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Marseille',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Marseille'),
        'value' => '44',
        'name' => 'Marseille',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Montpellier',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Montpellier'),
        'value' => '47',
        'name' => 'Montpellier',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nancy',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nancy'),
        'value' => '13',
        'name' => 'Nancy',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nantes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nantes'),
        'value' => '6',
        'name' => 'Nantes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nice',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nice'),
        'value' => '43',
        'name' => 'Nice',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nimes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nimes'),
        'value' => '42',
        'name' => 'Nimes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Paris',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Paris'),
        'value' => '17',
        'name' => 'Paris',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Poitiers',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Poitiers'),
        'value' => '15',
        'name' => 'Poitiers',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Reims',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Reims'),
        'value' => '10',
        'name' => 'Reims',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Rennes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Rennes'),
        'value' => '7',
        'name' => 'Rennes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Rouen',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Rouen'),
        'value' => '2',
        'name' => 'Rouen',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_St_Etienne',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('St Etienne'),
        'value' => '20',
        'name' => 'St_Etienne',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Strasbourg',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Strasbourg'),
        'value' => '12',
        'name' => 'Strasbourg',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Toulouse',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Toulouse'),
        'value' => '45',
        'name' => 'Toulouse',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Tours',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Tours'),
        'value' => '1',
        'name' => 'Tours',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Transfert_vers_autre_centre_CustomField_CDC_de_transfert',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Transfert_vers_autre_centre',
        'name' => 'CDC_de_transfert',
        'label' => E::ts('CDC de transfert'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '1',
        'help_pre' => E::ts('En cas de transfert vers un autre établissement'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'cdc_de_transfert_97',
        'option_group_id.name' => 'centre_de_don_20210419175120',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Transfert_vers_autre_centre_CustomField_Date_de_transfert_vers_un_autre_CDC',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Transfert_vers_autre_centre',
        'name' => 'Date_de_transfert_vers_un_autre_CDC',
        'label' => E::ts('Date de transfert vers un autre CDC'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'help_pre' => E::ts('En cas de transfert vers un autre établissement'),
        'text_length' => 255,
        'date_format' => 'mm/dd/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_de_transfert_vers_un_autre__98',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Transfert_vers_autre_centre_CustomField_Date_de_retour_du_corps_cendres',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Transfert_vers_autre_centre',
        'name' => 'Date_de_retour_du_corps_cendres',
        'label' => E::ts('Date de retour du corps/cendres'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'help_pre' => E::ts('Date expédition du corps ou des cendres du donneur par le centre l ayant pris en charge'),
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_de_retour_du_corps_cendres_101',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Transfert_vers_autre_centre_CustomField_Date_de_r_c_ption_du_corps_ou_des_cendres',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Transfert_vers_autre_centre',
        'name' => 'Date_de_r_c_ption_du_corps_ou_des_cendres',
        'label' => E::ts('Date de réception du corps ou des cendres'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'help_pre' => E::ts('Date de réception du corps ou des cendres envoyés par le centre l ayant pris en charge'),
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_de_r_c_ption_du_corps_ou_de_102',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
