<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_champs_caches',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'champs_caches',
        'title' => E::ts('champs caches'),
        'weight' => 16,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-05-27 13:45:04',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_champs_caches_CustomField_piece_prinicpale',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'champs_caches',
        'name' => 'piece_prinicpale',
        'label' => E::ts('piece prinicpale'),
        'html_type' => 'Text',
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'piece_prinicpale_183',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Utilisation2',
        'title' => E::ts('Utilisation du corps :: Utilisation2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Enseignement_L1_L2_L3',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Enseignement L1-L2-L3'),
        'value' => '1',
        'name' => 'Enseignement_L1_L2_L3',
        'description' => E::ts('TP/ED, UERB, Suture'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Enseignement_C2',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Enseignement C2'),
        'value' => '2',
        'name' => 'Enseignement_C2',
        'description' => E::ts('Deuxième cycle'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Enseignement_Internes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Enseignement Internes'),
        'value' => '3',
        'name' => 'Enseignement_Internes',
        'description' => E::ts('ECT, Entrainement des internes...'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Formation_continue',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Formation continue'),
        'value' => '6',
        'name' => 'Formation_continue',
        'description' => E::ts('Préparation aux concours, Enseignement à des praticiens hors workshops'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Recherche',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Recherche'),
        'value' => '5',
        'name' => 'Recherche',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Workshop_Acad_mique',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Workshop Académique'),
        'value' => '7',
        'name' => 'Workshop_Acad_mique',
        'description' => E::ts('Cours EANS, cours société savante, DU...'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Workshop_industrie',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Workshop industrie'),
        'value' => '4',
        'name' => 'Workshop_industrie',
        'description' => E::ts('Cours organisé par un industriel'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Ind_termin_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('En attente utilisation'),
        'value' => '8',
        'name' => 'Ind_termin_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_champs_caches_CustomField_toutes_utilisations',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'champs_caches',
        'name' => 'toutes_utilisations',
        'label' => E::ts('toutes utilisations'),
        'html_type' => 'Select',
        'default_value' => '8',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'toutes_utilisations_194',
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'title' => E::ts('Utilisation du corps :: Type de poièce 3'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Abdomen_Foie',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Abdomen - Foie'),
        'value' => '11',
        'name' => 'Abdomen_Foie',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Autre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Autre'),
        'value' => '12',
        'name' => 'Autre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Base_du_crane',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Base du crane'),
        'value' => '10',
        'name' => 'Base_du_crane',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Corps_entier_tronc',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Corps entier / tronc'),
        'value' => '1',
        'name' => 'Corps_entier_tronc',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Membre_inf_rieur',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Membre inférieur'),
        'value' => '3',
        'name' => 'Membre_inf_rieur',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Membre_sup_rieur',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Membre supérieur'),
        'value' => '2',
        'name' => 'Membre_sup_rieur',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Cerveau',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Cerveau'),
        'value' => '5',
        'name' => 'SNC_Cerveau',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Cerveau_fragments',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Cerveau fragments'),
        'value' => '9',
        'name' => 'SNC_Cerveau_fragments',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Cervelet',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Cervelet'),
        'value' => '6',
        'name' => 'SNC_Cervelet',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Moelle_pini_re',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Moelle épinière'),
        'value' => '7',
        'name' => 'SNC_Moelle_pini_re',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Tronc',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Tronc'),
        'value' => '8',
        'name' => 'SNC_Tronc',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_thorax',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Thorax - Coeur'),
        'value' => '13',
        'name' => 'thorax',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Thorax_Poumon',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Thorax - Poumon'),
        'value' => '14',
        'name' => 'Thorax_Poumon',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_T_te',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Tête'),
        'value' => '4',
        'name' => 'T_te',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Abdomen_rein',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Abdomen - rein'),
        'value' => '15',
        'name' => 'Abdomen - rein',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_champs_caches_CustomField_toutes_pieces',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'champs_caches',
        'name' => 'toutes_pieces',
        'label' => E::ts('toutes pieces'),
        'html_type' => 'Select',
        'default_value' => '1',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'toutes_pieces_195',
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_champs_caches_CustomField_centre_gestion_corps',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'champs_caches',
        'name' => 'centre_gestion_corps',
        'label' => E::ts('centre gestion corps'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'centre_gestion_corps_112',
        'filter' => 'action=get&contact_sub_type=CDC',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
