<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Prise_en_charge_au_d_c_s',
        'title' => E::ts('Prise en charge au décès'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Donateur'],
        'weight' => 9,
        'created_date' => '2021-07-21 13:46:19',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s_CustomField_N_de_d_c_s',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Prise_en_charge_au_d_c_s',
        'name' => 'N_de_d_c_s',
        'label' => E::ts('N° de décès'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'help_pre' => E::ts('DD#AAAA-NNNNN
DD : Département du centre d\'accueil des corps
AAAA: année
NNNNN: numéro (5 chiffres)'),
        'help_post' => E::ts('DOIT ETRE UNIQUE !'),
        'text_length' => 20,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'n_de_d_c_s_20',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s_CustomField_Date_d_arriv_e_au_CDC',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Prise_en_charge_au_d_c_s',
        'name' => 'Date_d_arriv_e_au_CDC',
        'label' => E::ts('Date arrivée au CDC'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_d_arriv_e_au_cdc_65',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'motif_de_refus_du_corps_20220416082140',
        'title' => E::ts('Motif de refus du corps'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Pas_de_refus',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Pas de refus'),
        'value' => '1',
        'name' => 'Pas_de_refus',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_CDC_non_pr_venu_avant_le_d_c_s',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('CDC non prévenu avant le décès'),
        'value' => '11',
        'name' => 'CDC non prévenu avant le décès',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_D_c_s_l_tranger',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Décès à l étranger'),
        'value' => '5',
        'name' => 'D_c_s_l_tranger',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_D_lai_d_pass_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Délai dépassé'),
        'value' => '2',
        'name' => 'D_lai_d_pass_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Etat_de_conservation_du_corps',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Etat de conservation du corps'),
        'value' => '8',
        'name' => 'Etat_de_conservation_du_corps',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Inconnu',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Inconnu'),
        'value' => '7',
        'name' => 'Inconnu',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Maladie_infectieuse',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Maladie infectieuse'),
        'value' => '3',
        'name' => 'Maladie_infectieuse',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Obstacle_m_dico_l_gal',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Obstacle médico-légal'),
        'value' => '4',
        'name' => 'Obstacle_m_dico_l_gal',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Pand_mie_COVID',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Pandémie COVID'),
        'value' => '10',
        'name' => 'Pandémie COVID',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Refus_famille',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Refus famille'),
        'value' => '9',
        'name' => 'Refus famille',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Transfert_vers_autre_centre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Prise en charge par un autre centre'),
        'value' => '6',
        'name' => 'Transfert_vers_autre_centre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_motif_de_refus_du_corps_20220416082140_OptionValue_Pi_ce_anatomique_isol_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
        'label' => E::ts('Pièce anatomique isolée'),
        'value' => '12',
        'name' => 'Pièce anatomique isolée',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s_CustomField_Motif_de_refus_du_corps',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Prise_en_charge_au_d_c_s',
        'name' => 'Motif_de_refus_du_corps',
        'label' => E::ts('Motif de refus du corps'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'motif_de_refus_du_corps_49',
        'option_group_id.name' => 'motif_de_refus_du_corps_20220416082140',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s_CustomField_Ville_de_d_c_s',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Prise_en_charge_au_d_c_s',
        'name' => 'Ville_de_d_c_s',
        'label' => E::ts('Ville de décès'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ville_de_d_c_s_38',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_lieu_de_d_c_s_20210418194524',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'lieu_de_d_c_s_20210418194524',
        'title' => E::ts('Lieu de décès'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_lieu_de_d_c_s_20210418194524_OptionValue_Domicile',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'lieu_de_d_c_s_20210418194524',
        'label' => E::ts('Domicile'),
        'value' => '1',
        'name' => 'Domicile',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_lieu_de_d_c_s_20210418194524_OptionValue_EHPAD',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'lieu_de_d_c_s_20210418194524',
        'label' => E::ts('EHPAD'),
        'value' => '8',
        'name' => 'EHPAD',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_lieu_de_d_c_s_20210418194524_OptionValue_H_pital_Clinique',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'lieu_de_d_c_s_20210418194524',
        'label' => E::ts('Hôpital, Clinique'),
        'value' => '7',
        'name' => 'H_pital_Clinique',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_lieu_de_d_c_s_20210418194524_OptionValue_Pompes_fun_bres',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'lieu_de_d_c_s_20210418194524',
        'label' => E::ts('Pompes funèbres'),
        'value' => '2',
        'name' => 'Pompes_fun_bres',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_lieu_de_d_c_s_20210418194524_OptionValue_Autre_centre_de_don_de_corps',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'lieu_de_d_c_s_20210418194524',
        'label' => E::ts('Autre centre de don de corps'),
        'value' => '3',
        'name' => 'Autre_centre_de_don_de_corps',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s_CustomField_Lieu_de_d_c_s',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Prise_en_charge_au_d_c_s',
        'name' => 'Lieu_de_d_c_s',
        'label' => E::ts('Lieu de prise en charge'),
        'html_type' => 'Select',
        'default_value' => '15',
        'is_searchable' => TRUE,
        'help_post' => E::ts('Lieu de prise en charge (peut différer du lieu de décès)'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'lieu_de_d_c_s_21',
        'option_group_id.name' => 'lieu_de_d_c_s_20210418194524',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s_CustomField_Pr_cision_lieu_prise_en_charge',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Prise_en_charge_au_d_c_s',
        'name' => 'Pr_cision_lieu_prise_en_charge',
        'label' => E::ts('Précision lieu prise en charge'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'pr_cision_lieu_prise_en_charge_35',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Prise_en_charge_au_d_c_s_CustomField_Ancien_N_DC',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Prise_en_charge_au_d_c_s',
        'name' => 'Ancien_N_DC',
        'label' => E::ts('Ancien N° DC'),
        'html_type' => 'Text',
        'is_active' => FALSE,
        'is_view' => TRUE,
        'text_length' => 15,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ancien_n_dc_96',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
