<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_animal',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'animal',
        'title' => E::ts('animal'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Animal'],
        'weight' => 13,
        'collapse_adv_display' => TRUE,
        'created_date' => '2025-08-28 16:30:32',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Provenance',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'animal_Provenance',
        'title' => E::ts('animal :: Provenance'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Provenance_OptionValue_INRAe_Nouzilly',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'animal_Provenance',
        'label' => E::ts('INRAe Nouzilly'),
        'value' => '1',
        'name' => 'INRAe_Nouzilly',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Provenance_OptionValue_Animalerie_facult_M_decine',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'animal_Provenance',
        'label' => E::ts('Animalerie faculté Médecine'),
        'value' => '2',
        'name' => 'Animalerie_facult_M_decine',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Provenance_OptionValue_Beauval',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'animal_Provenance',
        'label' => E::ts('Beauval'),
        'value' => '3',
        'name' => 'Beauval',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_animal_CustomField_Provenance',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'animal',
        'name' => 'Provenance',
        'label' => E::ts('Provenance'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'provenance_198',
        'option_group_id.name' => 'animal_Provenance',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Esp_ce',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'animal_Esp_ce',
        'title' => E::ts('animal :: Espèce'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Esp_ce_OptionValue_Brebis',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'animal_Esp_ce',
        'label' => E::ts('Brebis'),
        'value' => '1',
        'name' => 'Brebis',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Esp_ce_OptionValue_Macaque_fascicularis',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'animal_Esp_ce',
        'label' => E::ts('Macaque fascicularis'),
        'value' => '2',
        'name' => 'Macaque_fascicularis',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_animal_CustomField_Esp_ce',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'animal',
        'name' => 'Esp_ce',
        'label' => E::ts('Espèce'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'esp_ce_199',
        'option_group_id.name' => 'animal_Esp_ce',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_animal_CustomField_Ref_avis_comit_thique',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'animal',
        'name' => 'Ref_avis_comit_thique',
        'label' => E::ts('Ref avis comité éthique'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ref_avis_comit_thique_200',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_animal_CustomField_date_avis_comit_thique',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'animal',
        'name' => 'date_avis_comit_thique',
        'label' => E::ts('date avis comité éthique'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_avis_comit_thique_201',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_animal_CustomField_Poids_au_d_c_s',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'animal',
        'name' => 'Poids_au_d_c_s',
        'label' => E::ts('Poids au décès'),
        'html_type' => 'Text',
        'text_length' => 10,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'poids_au_d_c_s_202',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Euthanasie',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'animal_Euthanasie',
        'title' => E::ts('animal :: Euthanasie'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_animal_Euthanasie_OptionValue_Dolethal_1ml_kg',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'animal_Euthanasie',
        'label' => E::ts('Dolethal 1ml/kg'),
        'value' => '1',
        'name' => 'Dolethal_1ml_kg',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_animal_CustomField_Euthanasie',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'animal',
        'name' => 'Euthanasie',
        'label' => E::ts('Euthanasie'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'euthanasie_203',
        'option_group_id.name' => 'animal_Euthanasie',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
