<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Promesse_de_don',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Promesse_de_don',
        'title' => E::ts('Promesse de don'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Donateur'],
        'weight' => 7,
        'created_date' => '2021-07-21 13:38:50',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'centre_de_don_20210419175120',
        'title' => E::ts('Centre de don'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Amiens',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Amiens'),
        'value' => '4',
        'name' => 'Amiens',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Angers',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Angers'),
        'value' => '14',
        'name' => 'Angers',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Besan_on',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Besançon'),
        'value' => '9',
        'name' => 'Besan_on',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Bordeaux',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Bordeaux'),
        'value' => '46',
        'name' => 'Bordeaux',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Brest',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Brest'),
        'value' => '8',
        'name' => 'Brest',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Caen',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Caen'),
        'value' => '3',
        'name' => 'Caen',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Clermont_Ferrand',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Clermont-Ferrand'),
        'value' => '18',
        'name' => 'Clermont_Ferrand',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Dijon',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Dijon'),
        'value' => '11',
        'name' => 'Dijon',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Grenoble',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Grenoble'),
        'value' => '41',
        'name' => 'Grenoble',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Lille',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Lille'),
        'value' => '5',
        'name' => 'Lille',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Limoges',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Limoges'),
        'value' => '16',
        'name' => 'Limoges',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Lyon',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Lyon'),
        'value' => '19',
        'name' => 'Lyon',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Marseille',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Marseille'),
        'value' => '44',
        'name' => 'Marseille',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Montpellier',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Montpellier'),
        'value' => '47',
        'name' => 'Montpellier',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nancy',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nancy'),
        'value' => '13',
        'name' => 'Nancy',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nantes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nantes'),
        'value' => '6',
        'name' => 'Nantes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nice',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nice'),
        'value' => '43',
        'name' => 'Nice',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Nimes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Nimes'),
        'value' => '42',
        'name' => 'Nimes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Paris',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Paris'),
        'value' => '17',
        'name' => 'Paris',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Poitiers',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Poitiers'),
        'value' => '15',
        'name' => 'Poitiers',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Reims',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Reims'),
        'value' => '10',
        'name' => 'Reims',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Rennes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Rennes'),
        'value' => '7',
        'name' => 'Rennes',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Rouen',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Rouen'),
        'value' => '2',
        'name' => 'Rouen',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_St_Etienne',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('St Etienne'),
        'value' => '20',
        'name' => 'St_Etienne',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Strasbourg',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Strasbourg'),
        'value' => '12',
        'name' => 'Strasbourg',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Toulouse',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Toulouse'),
        'value' => '45',
        'name' => 'Toulouse',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_centre_de_don_20210419175120_OptionValue_Tours',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'centre_de_don_20210419175120',
        'label' => E::ts('Tours'),
        'value' => '1',
        'name' => 'Tours',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_Centre_de_don',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'Centre_de_don',
        'label' => E::ts('Centre de don'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '1',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'centre_de_don_34',
        'option_group_id.name' => 'centre_de_don_20210419175120',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_N_de_don',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'N_de_don',
        'label' => E::ts('N° de don'),
        'html_type' => 'Text',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'help_pre' => E::ts('DD#AAAA-NNNNN
DD : département du centre d\'accueil des corps
AAAA: année
NNNNN: numéro (5 chiffres)'),
        'text_length' => 20,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'n_de_don_14',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_Date_du_don',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'Date_du_don',
        'label' => E::ts('Date du don'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_required' => TRUE,
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_du_don_15',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_Refus_personne_referente',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'Refus_personne_referente',
        'label' => E::ts('Refus personne referente'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '0',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'refus_personne_referente_70',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie',
        'title' => E::ts('Promesse de don :: Prévenir personne référence de la cérémonie'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie_OptionValue_Volont_inconnue',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie',
        'label' => E::ts('Volonté inconnue'),
        'value' => '0',
        'name' => 'Volont_inconnue',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie_OptionValue_Oui',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie',
        'label' => E::ts('Oui'),
        'value' => '1',
        'name' => 'Oui',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie_OptionValue_Non',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie',
        'label' => E::ts('Non'),
        'value' => '2',
        'name' => 'Non',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_Pr_venir_personne_r_f_rence_de_la_c_r_monie',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'Pr_venir_personne_r_f_rence_de_la_c_r_monie',
        'label' => E::ts('Prévenir référent de cérémonie'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '0',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'pr_venir_personne_r_f_rence_de_l_69',
        'option_group_id.name' => 'Promesse_de_don_Pr_venir_personne_r_f_rence_de_la_c_r_monie',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Souhait_lecture_nom',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Promesse_de_don_Souhait_lecture_nom',
        'title' => E::ts('Promesse de don :: Souhait lecture nom'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Souhait_lecture_nom_OptionValue_Volont_inconnue',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Promesse_de_don_Souhait_lecture_nom',
        'label' => E::ts('Volonté inconnue'),
        'value' => '0',
        'name' => 'Volont_inconnue',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Souhait_lecture_nom_OptionValue_Oui',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Promesse_de_don_Souhait_lecture_nom',
        'label' => E::ts('Oui'),
        'value' => '1',
        'name' => 'Oui',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Promesse_de_don_Souhait_lecture_nom_OptionValue_Non',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Promesse_de_don_Souhait_lecture_nom',
        'label' => E::ts('Non'),
        'value' => '2',
        'name' => 'Non',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_Souhait_lecture_nom',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'Souhait_lecture_nom',
        'label' => E::ts('Souhait lecture nom'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '0',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'souhait_lecture_nom_67',
        'option_group_id.name' => 'Promesse_de_don_Souhait_lecture_nom',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_Souhiat_affichage_st_le',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'Souhiat_affichage_st_le',
        'label' => E::ts('Souhait affichage stèle'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '0',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'souhiat_affichage_st_le_68',
        'option_group_id.name' => 'Promesse_de_don_Souhait_lecture_nom',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_souhait_20220501001624',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'devenir_souhait__20220501001624',
        'title' => E::ts('Devenir souhaité'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_souhait_20220501001624_OptionValue_Cr_mation_et_dispersion_par_le_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_souhait__20220501001624',
        'label' => E::ts('Crémation et dispersion par le CDC'),
        'value' => '1',
        'name' => 'Cr_mation_et_dispersion_par_le_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_souhait_20220501001624_OptionValue_Restitution_des_cendres',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_souhait__20220501001624',
        'label' => E::ts('Restitution des cendres'),
        'value' => '2',
        'name' => 'Restitution_des_cendres',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_souhait_20220501001624_OptionValue_Restitution_du_corps',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_souhait__20220501001624',
        'label' => E::ts('Restitution du corps'),
        'value' => '3',
        'name' => 'Restitution_du_corps',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_souhait_20220501001624_OptionValue_Absence_de_volont_particuli_re',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_souhait__20220501001624',
        'label' => E::ts('Absence de volonté particulière'),
        'value' => '4',
        'name' => 'Absence de volonté particulière',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_souhait_20220501001624_OptionValue_Inhumation',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_souhait__20220501001624',
        'label' => E::ts('Inhumation'),
        'value' => '5',
        'name' => 'Inhumation',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_Devenir_souhait_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'Devenir_souhait_',
        'label' => E::ts('Devenir souhaité'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'devenir_souhait__51',
        'option_group_id.name' => 'devenir_souhait__20220501001624',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_RGPD_sign_e',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'RGPD_sign_e',
        'label' => E::ts('RGPD signée'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '0',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'rgpd_sign_e_50',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_ancien_n_don',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'ancien_n_don',
        'label' => E::ts('ancien n°don'),
        'html_type' => 'Text',
        'is_active' => NULL,
        'is_view' => TRUE,
        'text_length' => 15,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ancien_n_don_94',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Promesse_de_don_CustomField_MUTAC',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Promesse_de_don',
        'name' => 'MUTAC',
        'label' => E::ts('MUTAC'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '0',
        'is_searchable' => TRUE,
        'is_active' => NULL,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'mutac_118',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
