<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Arriv_e_du_corps_new',
        'title' => E::ts('Arrivée du corps'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Donateur'],
        'style' => 'Tab',
        'weight' => 5,
        'collapse_adv_display' => TRUE,
        'created_date' => '2024-05-19 18:11:04',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_Signataire_certificat_de_d_c_s',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'Signataire_certificat_de_d_c_s',
        'label' => E::ts('Signataire certificat de décès (nom, tel, ville)'),
        'html_type' => 'Text',
        'is_required' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'signataire_certificat_de_d_c_s_120',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_Retrait_Stimulateur_piles',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Arriv_e_du_corps_new_Retrait_Stimulateur_piles',
        'title' => E::ts('Arrivée du corps new :: Retrait Stimulateur à piles'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_Retrait_Stimulateur_piles_OptionValue_pas_de_pacemaker',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_Retrait_Stimulateur_piles',
        'label' => E::ts('pas de pacemaker'),
        'value' => '1',
        'name' => 'pas_de_pacemaker',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_Retrait_Stimulateur_piles_OptionValue_retrait_du_pacemaker_au_labo',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_Retrait_Stimulateur_piles',
        'label' => E::ts('retrait du pacemaker au labo'),
        'value' => '2',
        'name' => 'retrait_du_pacemaker_au_labo',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_Retrait_Stimulateur_piles_OptionValue_retrait_du_pacemaker_avant_labo',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_Retrait_Stimulateur_piles',
        'label' => E::ts('retrait du pacemaker avant labo'),
        'value' => '3',
        'name' => 'retrait_du_pacemaker_avant_labo',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_Retrait_Stimulateur_piles_OptionValue_A_v_rifier',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_Retrait_Stimulateur_piles',
        'label' => E::ts('a vérifier'),
        'value' => '4',
        'name' => 'A vérifier',
        'is_default' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_Retrait_Stimulateur_piles',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'Retrait_Stimulateur_piles',
        'label' => E::ts('Retrait Stimulateur à piles'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'retrait_stimulateur_piles_175',
        'option_group_id.name' => 'Arriv_e_du_corps_new_Retrait_Stimulateur_piles',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_VIH',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Arriv_e_du_corps_new_S_rologie_VIH',
        'title' => E::ts('Arrivée du corps new :: Sérologie VIH'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_VIH_OptionValue_Non_realis_es',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_VIH',
        'label' => E::ts('non realisée'),
        'value' => '1',
        'name' => 'Non_realis_es',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_VIH_OptionValue_Positive',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_VIH',
        'label' => E::ts('positive'),
        'value' => '2',
        'name' => 'Positive',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_VIH_OptionValue_n_gative',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_VIH',
        'label' => E::ts('négative'),
        'value' => '3',
        'name' => 'n_gative',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_S_rologie_VIH',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'S_rologie_VIH',
        'label' => E::ts('Sérologie VIH'),
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 's_rologie_vih_176',
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_VIH',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_HBV',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Arriv_e_du_corps_new_S_rologie_HBV',
        'title' => E::ts('Arrivée du corps new :: Sérologie HBV'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_HBV_OptionValue_non_r_alis_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_HBV',
        'label' => E::ts('non réalisée'),
        'value' => '1',
        'name' => 'non_r_alis_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_HBV_OptionValue_positive',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_HBV',
        'label' => E::ts('positive'),
        'value' => '2',
        'name' => 'positive',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_HBV_OptionValue_n_gative',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_HBV',
        'label' => E::ts('négative'),
        'value' => '3',
        'name' => 'n_gative',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_S_rologie_HBV',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'S_rologie_HBV',
        'label' => E::ts('Sérologie HBV'),
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 's_rologie_hbv_177',
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_HBV',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_COVID',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Arriv_e_du_corps_new_S_rologie_COVID',
        'title' => E::ts('Arrivée du corps new :: Sérologie COVID'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_COVID_OptionValue_non_r_alis_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_COVID',
        'label' => E::ts('non réalisée'),
        'value' => '1',
        'name' => 'non_r_alis_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_COVID_OptionValue_positive',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_COVID',
        'label' => E::ts('positive'),
        'value' => '2',
        'name' => 'positive',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_S_rologie_COVID_OptionValue_n_gative',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_COVID',
        'label' => E::ts('négative'),
        'value' => '3',
        'name' => 'n_gative',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_S_rologie_COVID',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'S_rologie_COVID',
        'label' => E::ts('Sérologie COVID'),
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 's_rologie_covid_178',
        'option_group_id.name' => 'Arriv_e_du_corps_new_S_rologie_COVID',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_PCR_COVID',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Arriv_e_du_corps_new_PCR_COVID',
        'title' => E::ts('Arrivée du corps new :: PCR COVID'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_PCR_COVID_OptionValue_non_r_alis_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_PCR_COVID',
        'label' => E::ts('non réalisée'),
        'value' => '1',
        'name' => 'non_r_alis_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_PCR_COVID_OptionValue_positive',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_PCR_COVID',
        'label' => E::ts('positive'),
        'value' => '2',
        'name' => 'positive',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_new_PCR_COVID_OptionValue_n_gative',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_new_PCR_COVID',
        'label' => E::ts('négative'),
        'value' => '3',
        'name' => 'n_gative',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_PCR_COVID',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'PCR_COVID',
        'label' => E::ts('PCR COVID selles'),
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'pcr_covid_179',
        'option_group_id.name' => 'Arriv_e_du_corps_new_PCR_COVID',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_PCR_COVID_nasopharyng_e',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Arriv_e_du_corps_PCR_COVID_nasopharyng_e',
        'title' => E::ts('Arrivée du corps :: PCR COVID nasopharyngée'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_PCR_COVID_nasopharyng_e_OptionValue_non_r_alis_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_PCR_COVID_nasopharyng_e',
        'label' => E::ts('non réalisée'),
        'value' => '1',
        'name' => 'non_r_alis_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_PCR_COVID_nasopharyng_e_OptionValue_positive',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_PCR_COVID_nasopharyng_e',
        'label' => E::ts('positive'),
        'value' => '2',
        'name' => 'positive',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Arriv_e_du_corps_PCR_COVID_nasopharyng_e_OptionValue_n_gative',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Arriv_e_du_corps_PCR_COVID_nasopharyng_e',
        'label' => E::ts('négative'),
        'value' => '3',
        'name' => 'n_gative',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_PCR_COVID_nasopharyng_e',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'PCR_COVID_nasopharyng_e',
        'label' => E::ts('PCR COVID nasopharyngée'),
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'pcr_covid_nasopharyng_e_180',
        'option_group_id.name' => 'Arriv_e_du_corps_PCR_COVID_nasopharyng_e',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_Effets_personnels_retir_s',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'Effets_personnels_retir_s',
        'label' => E::ts('Effets personnels retirés'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'default_value' => 'Aucun',
        'is_searchable' => TRUE,
        'help_pre' => E::ts('En cas d\'effets personnels de valeur retrouvés sur le donneur : 1) décrivez les le plus précisément possible 2) imprimez le certificat de retrait et joignez-le à l\'objet avant de le remettre au secrétariat Action -&gt; Créer CiviOfficeDocument : Reçu effets personnels : cocher créer une activité Effets Personnels'),
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 6,
        'column_name' => 'effets_personnels_retir_s_194',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Arriv_e_du_corps_new_CustomField_Commentaire',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Arriv_e_du_corps_new',
        'name' => 'Commentaire',
        'label' => E::ts('Commentaire'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 6,
        'column_name' => 'commentaire_182',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
