<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_infos_personnel',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'infos_personnel',
        'title' => E::ts('Informations Personnel'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Personnel'],
        'weight' => 15,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_infos_personnel_CustomField_Date_debut_fonctions',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'infos_personnel',
        'name' => 'Date_debut_fonctions',
        'label' => E::ts('Date du début des fonctions'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'column_name' => 'date_du_d_but_des_fonctions_123',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_infos_personnel_CustomField_Date_fin_fonctions',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'infos_personnel',
        'name' => 'Date_fin_fonctions',
        'label' => E::ts('Date de la fin des fonctions'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'column_name' => 'date_de_la_fin_des_fonctions_124',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_M_tier',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Informations_Personnel_M_tier',
        'title' => E::ts('Informations Personnel :: Métier'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_M_tier_OptionValue_BIATS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_M_tier',
        'label' => E::ts('BIATS'),
        'value' => '1',
        'name' => 'BIATS',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_M_tier_OptionValue_Enseignant_chercheur_chercheur',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_M_tier',
        'label' => E::ts('Enseignant chercheur - chercheur'),
        'value' => '2',
        'name' => 'Enseignant_chercheur_chercheur',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_infos_personnel_CustomField_M_tier',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'infos_personnel',
        'name' => 'M_tier',
        'label' => E::ts('Métier'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'm_tier_188',
        'option_group_id.name' => 'Informations_Personnel_M_tier',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Cat_gorie',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Informations_Personnel_Cat_gorie',
        'title' => E::ts('Informations Personnel :: Catégorie'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Cat_gorie_OptionValue_7fc56270e7a70fa81a5935b72eacbe2',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_Cat_gorie',
        'label' => E::ts('A'),
        'value' => '1',
        'name' => '7fc56270e7a70fa81a5935b72eacbe2',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Cat_gorie_OptionValue_9d5ed678fe57bcca610140957afab57',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_Cat_gorie',
        'label' => E::ts('B'),
        'value' => '2',
        'name' => '9d5ed678fe57bcca610140957afab57',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Cat_gorie_OptionValue_0d61f8370cad1d412f80b84d143e125',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_Cat_gorie',
        'label' => E::ts('C'),
        'value' => '3',
        'name' => '0d61f8370cad1d412f80b84d143e125',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_infos_personnel_CustomField_Cat_gorie',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'infos_personnel',
        'name' => 'Cat_gorie',
        'label' => E::ts('Catégorie'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'cat_gorie_189',
        'option_group_id.name' => 'Informations_Personnel_Cat_gorie',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Informations_Personnel_BAP',
        'title' => E::ts('Informations Personnel :: BAP'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP_OptionValue_7fc56270e7a70fa81a5935b72eacbe2',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_BAP',
        'label' => E::ts('A'),
        'value' => '1',
        'name' => '7fc56270e7a70fa81a5935b72eacbe2',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP_OptionValue_9d5ed678fe57bcca610140957afab57',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_BAP',
        'label' => E::ts('B'),
        'value' => '2',
        'name' => '9d5ed678fe57bcca610140957afab57',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP_OptionValue_0d61f8370cad1d412f80b84d143e125',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_BAP',
        'label' => E::ts('C'),
        'value' => '3',
        'name' => '0d61f8370cad1d412f80b84d143e125',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP_OptionValue_f623e75af30e62bbd73d6df5b50bb7b',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_BAP',
        'label' => E::ts('D'),
        'value' => '4',
        'name' => 'f623e75af30e62bbd73d6df5b50bb7b',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP_OptionValue_3a3ea00cfc35332cedf6e5e9a32e94d',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_BAP',
        'label' => E::ts('E'),
        'value' => '5',
        'name' => '3a3ea00cfc35332cedf6e5e9a32e94d',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP_OptionValue_800618943025315f869e4e1f0947101',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_BAP',
        'label' => E::ts('F'),
        'value' => '6',
        'name' => '800618943025315f869e4e1f0947101',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_BAP_OptionValue_ff44570aca8241914870afbc310cdb8',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_BAP',
        'label' => E::ts('J'),
        'value' => '7',
        'name' => 'ff44570aca8241914870afbc310cdb8',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_infos_personnel_CustomField_BAP',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'infos_personnel',
        'name' => 'BAP',
        'label' => E::ts('BAP'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'bap_190',
        'option_group_id.name' => 'Informations_Personnel_BAP',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Contrat',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Informations_Personnel_Contrat',
        'title' => E::ts('Informations Personnel :: Contrat'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Contrat_OptionValue_Titulaire',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_Contrat',
        'label' => E::ts('Titulaire'),
        'value' => '1',
        'name' => 'Titulaire',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Contrat_OptionValue_CDD',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_Contrat',
        'label' => E::ts('CDD'),
        'value' => '2',
        'name' => 'CDD',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Informations_Personnel_Contrat_OptionValue_CDI',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Informations_Personnel_Contrat',
        'label' => E::ts('CDI'),
        'value' => '3',
        'name' => 'CDI',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_infos_personnel_CustomField_Contrat',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'infos_personnel',
        'name' => 'Contrat',
        'label' => E::ts('Contrat'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'contrat_191',
        'option_group_id.name' => 'Informations_Personnel_Contrat',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
