<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Utilisation_du_corps',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps',
        'title' => E::ts('Utilisation du corps'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Donateur', 'Animal'],
        'style' => 'Tab with table',
        'weight' => 12,
        'is_multiple' => TRUE,
        'collapse_adv_display' => TRUE,
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_N_de_pi_ce_ou_de_corps',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'N_de_pi_ce_ou_de_corps',
        'label' => E::ts('N° de pièce ou de corps'),
        'html_type' => 'Text',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'text_length' => 12,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'n_de_pi_ce_ou_de_corps_165',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'title' => E::ts('Utilisation du corps :: Type de poièce 3'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Abdomen_Foie',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Abdomen - Foie'),
        'value' => '11',
        'name' => 'Abdomen_Foie',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Autre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Autre'),
        'value' => '12',
        'name' => 'Autre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Base_du_crane',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Base du crane'),
        'value' => '10',
        'name' => 'Base_du_crane',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Corps_entier_tronc',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Corps entier / tronc'),
        'value' => '1',
        'name' => 'Corps_entier_tronc',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Membre_inf_rieur',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Membre inférieur'),
        'value' => '3',
        'name' => 'Membre_inf_rieur',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Membre_sup_rieur',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Membre supérieur'),
        'value' => '2',
        'name' => 'Membre_sup_rieur',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Cerveau',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Cerveau'),
        'value' => '5',
        'name' => 'SNC_Cerveau',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Cerveau_fragments',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Cerveau fragments'),
        'value' => '9',
        'name' => 'SNC_Cerveau_fragments',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Cervelet',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Cervelet'),
        'value' => '6',
        'name' => 'SNC_Cervelet',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Moelle_pini_re',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Moelle épinière'),
        'value' => '7',
        'name' => 'SNC_Moelle_pini_re',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_SNC_Tronc',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('SNC - Tronc'),
        'value' => '8',
        'name' => 'SNC_Tronc',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_thorax',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Thorax - Coeur'),
        'value' => '13',
        'name' => 'thorax',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Thorax_Poumon',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Thorax - Poumon'),
        'value' => '14',
        'name' => 'Thorax_Poumon',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_T_te',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Tête'),
        'value' => '4',
        'name' => 'T_te',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Type_de_poi_ce_3_OptionValue_Abdomen_rein',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'label' => E::ts('Abdomen - rein'),
        'value' => '15',
        'name' => 'Abdomen - rein',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Type_de_poi_ce_3',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Type_de_poi_ce_3',
        'label' => E::ts('Type de pièce'),
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'type_de_poi_ce_3_157',
        'option_group_id.name' => 'Utilisation_du_corps_Type_de_poi_ce_3',
        'serialize' => 1,
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_cote2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_cote2',
        'title' => E::ts('Utilisation du corps :: cote2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_cote2_OptionValue_Droit',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_cote2',
        'label' => E::ts('Droit'),
        'value' => '1',
        'name' => 'Droit',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_cote2_OptionValue_Gauche',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_cote2',
        'label' => E::ts('Gauche'),
        'value' => '2',
        'name' => 'Gauche',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_cote2_OptionValue_Non_applicable',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_cote2',
        'label' => E::ts('Non applicable'),
        'value' => '3',
        'name' => 'Non_applicable',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_cote2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'cote2',
        'label' => E::ts('Côté'),
        'html_type' => 'Select',
        'default_value' => '3',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'cote2_166',
        'option_group_id.name' => 'Utilisation_du_corps_cote2',
        'serialize' => 1,
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Pr_par_par',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Pr_par_par',
        'label' => E::ts('Préparé par'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'pr_par_par_131',
        'filter' => 'action=get&contact_sub_type=Personnel',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Utilisation2',
        'title' => E::ts('Utilisation du corps :: Utilisation2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Enseignement_L1_L2_L3',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Enseignement L1-L2-L3'),
        'value' => '1',
        'name' => 'Enseignement_L1_L2_L3',
        'description' => E::ts('TP/ED, UERB, Suture'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Enseignement_C2',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Enseignement C2'),
        'value' => '2',
        'name' => 'Enseignement_C2',
        'description' => E::ts('Deuxième cycle'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Enseignement_Internes',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Enseignement Internes'),
        'value' => '3',
        'name' => 'Enseignement_Internes',
        'description' => E::ts('ECT, Entrainement des internes...'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Formation_continue',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Formation continue'),
        'value' => '6',
        'name' => 'Formation_continue',
        'description' => E::ts('Préparation aux concours, Enseignement à des praticiens hors workshops'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Recherche',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Recherche'),
        'value' => '5',
        'name' => 'Recherche',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Workshop_Acad_mique',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Workshop Académique'),
        'value' => '7',
        'name' => 'Workshop_Acad_mique',
        'description' => E::ts('Cours EANS, cours société savante, DU...'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Workshop_industrie',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('Workshop industrie'),
        'value' => '4',
        'name' => 'Workshop_industrie',
        'description' => E::ts('Cours organisé par un industriel'),
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Utilisation2_OptionValue_Ind_termin_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'label' => E::ts('En attente utilisation'),
        'value' => '8',
        'name' => 'Ind_termin_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Utilisation2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Utilisation2',
        'label' => E::ts('Utilisation'),
        'html_type' => 'Select',
        'default_value' => '8',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'utilisation2_158',
        'option_group_id.name' => 'Utilisation_du_corps_Utilisation2',
        'serialize' => 1,
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'title' => E::ts('Utilisation du corps :: Protocole de recherche ex vivo2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Autre',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Autre'),
        'value' => '1',
        'name' => 'Autre',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Banque_Pathologies',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Banque Pathologies'),
        'value' => '2',
        'name' => 'Banque_Pathologies',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Central_Sulcus_inside_out_Alex_Morrichon_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Central Sulcus inside out (Alex Morrichon)'),
        'value' => '20',
        'name' => 'Central Sulcus inside out (Alex Morrichon)',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Central_Sulcus_vasculature_Etie',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Central Sulcus vasculature (Etienne Dugast)'),
        'value' => '19',
        'name' => 'Central_Sulcus_vasculature_Etie',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Chiasma_voies_optiques',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Chiasma voies optiques'),
        'value' => '3',
        'name' => 'Chiasma_voies_optiques',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Fibratlas',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Fibratlas'),
        'value' => '4',
        'name' => 'Fibratlas',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Fibravasc',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Fibravasc'),
        'value' => '5',
        'name' => 'Fibravasc',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Fornix_Vasculature_Euan_Strachan_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Fornix Vasculature (Euan Strachan)'),
        'value' => '17',
        'name' => 'Fornix Vasculature (Euan Strachan)',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_FRM_tronc',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('FRM - tronc'),
        'value' => '6',
        'name' => 'FRM_tronc',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_HBP',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('HBP'),
        'value' => '7',
        'name' => 'HBP',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Ifopasuba',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Ifopasuba'),
        'value' => '8',
        'name' => 'Ifopasuba',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_inside_out_Guillaume_Dannhoff_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('inside-out (Guillaume Dannhoff)'),
        'value' => '22',
        'name' => 'inside-out (Guillaume Dannhoff)',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_inside_out_IFOF',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('inside-out IFOF'),
        'value' => '21',
        'name' => 'inside-out IFOF',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Klingler_brebis',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Klingler brebis'),
        'value' => '9',
        'name' => 'Klingler_brebis',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Macaque',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Macaque'),
        'value' => '13',
        'name' => 'Macaque',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Moelle',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Moelle'),
        'value' => '14',
        'name' => 'Moelle',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Nerf_trijumeau_LMT',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Nerf trijumeau LMT'),
        'value' => '15',
        'name' => 'Nerf_trijumeau_LMT',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Pas_de_protocole',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Pas de protocole'),
        'value' => '11',
        'name' => 'Pas_de_protocole',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Scanner_MEDIT_Martin_Charron_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Scanner MEDIT (Martin Charron)'),
        'value' => '18',
        'name' => 'Scanner_MEDIT_Martin_Charron_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Stratum_Calcarinum_Martin_Charron_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Stratum Calcarinum (Martin Charron)'),
        'value' => '16',
        'name' => 'Stratum Calcarinum (Martin Charron)',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_SUMMIT',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('SUMMIT'),
        'value' => '12',
        'name' => 'SUMMIT',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Protocole_de_recherche_ex_vivo2_OptionValue_Tronc_c_r_bral',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Tronc cérébral'),
        'value' => '10',
        'name' => 'Tronc_c_r_bral',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Protocole_de_recherche_ex_vivo2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Protocole_de_recherche_ex_vivo2',
        'label' => E::ts('Protocole de recherche ex vivo'),
        'html_type' => 'Select',
        'default_value' => '11',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'protocole_de_recherche_ex_vivo2_159',
        'option_group_id.name' => 'Utilisation_du_corps_Protocole_de_recherche_ex_vivo2',
        'serialize' => 1,
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Compl_ment',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Compl_ment',
        'label' => E::ts('Complément ou identifiant'),
        'html_type' => 'Text',
        'help_post' => E::ts('Si multiple, séparer les entrées par des virgules'),
        'text_length' => 500,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'compl_ment_ou_identifiant_135',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_D_lai_en_heure_entre_d_c_s_h_0_et_injection',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'D_lai_en_heure_entre_d_c_s_h_0_et_injection',
        'label' => E::ts('Délai en heures entre décès (h=0) et injection'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'help_pre' => E::ts('Si injection : délai depuis le décès. Pas injection : notez -1. Délai inconnu : notez -5'),
        'help_post' => E::ts('Si injection : délai depuis le décès. Pas injection : notez -1. Délai inconnu : notez -5'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'd_lai_en_heures_entre_d_c_s_h_0__136',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Site_inject_',
        'title' => E::ts('Utilisation du corps :: Site injecté'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_A_Basilaire',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('A. Basilaire'),
        'value' => '1',
        'name' => 'A_Basilaire',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_A_carotide_interne_D',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('A. carotide interne D'),
        'value' => '2',
        'name' => 'A_carotide_interne_D',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_A_carotide_interne_G',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('A. carotide interne G'),
        'value' => '3',
        'name' => 'A_carotide_interne_G',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_A_F_morale_D',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('A. Fémorale D'),
        'value' => '6',
        'name' => 'A_F_morale_D',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_A_F_morale_G',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('A. Fémorale G'),
        'value' => '7',
        'name' => 'A_F_morale_G',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_A_vert_brale_D',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('A. vertébrale D'),
        'value' => '4',
        'name' => 'A_vert_brale_D',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_A_vert_brale_G',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('A. vertébrale G'),
        'value' => '5',
        'name' => 'A_vert_brale_G',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_ACA_D',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('ACA D'),
        'value' => '10',
        'name' => 'ACA_D',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_ACA_G',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('ACA G'),
        'value' => '11',
        'name' => 'ACA_G',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_MCA_D',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('MCA D'),
        'value' => '12',
        'name' => 'MCA_D',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_MCA_G',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('MCA G'),
        'value' => '13',
        'name' => 'MCA_G',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_V_jugulaire_interne_D',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('V. jugulaire interne D'),
        'value' => '8',
        'name' => 'V_jugulaire_interne_D',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Site_inject_OptionValue_V_jugulaire_interne_G',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'label' => E::ts('V. jugulaire interne G'),
        'value' => '9',
        'name' => 'V_jugulaire_interne_G',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Site_inject_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Site_inject_',
        'label' => E::ts('Site injecté'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'site_inject__160',
        'option_group_id.name' => 'Utilisation_du_corps_Site_inject_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_M_dium_inject_',
        'title' => E::ts('Utilisation du corps :: Médium injecté'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_Formol_tamponn_4_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('Formol 4% tamponné'),
        'value' => '1',
        'name' => 'Formol_tamponn_4_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_Formol_37_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('Formol 37% dilué au 1/10'),
        'value' => '2',
        'name' => 'Formol_37_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_Latex_color_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('Latex'),
        'value' => '3',
        'name' => 'Latex_color_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_G_lose_color_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('Gélose'),
        'value' => '4',
        'name' => 'G_lose_color_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_Formaldehyde_pr_par_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('Formaldehyde préparé'),
        'value' => '5',
        'name' => 'Formaldehyde_pr_par_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_Serum_sal_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('Serum salé'),
        'value' => '6',
        'name' => 'Serum_sal_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_ARTHYL_FORMOL',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('ARTHYL - FORMOL'),
        'value' => '7',
        'name' => 'ARTHYL - FORMOL',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_M_dium_inject_OptionValue_Silicone',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'label' => E::ts('Silicone'),
        'value' => '8',
        'name' => 'Silicone',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_M_dium_inject_',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'M_dium_inject_',
        'label' => E::ts('Médium injecté'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'm_dium_inject__138',
        'option_group_id.name' => 'Utilisation_du_corps_M_dium_inject_',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_D_lai_en_heure_entre_d_c_s_h_0_et_pr_l_vement_ventuel',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'D_lai_en_heure_entre_d_c_s_h_0_et_pr_l_vement_ventuel',
        'label' => E::ts('Délai en heure entre décès (h=0) et prélèvement éventuel'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'help_pre' => E::ts('Si prélèvement : délai depuis le décès. Pas de prélèvement : notez -1. Délai inconnu : notez -5'),
        'help_post' => E::ts('Si prélèvement : délai depuis le décès. Pas de prélèvement : notez -1. Délai inconnu : notez -5'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'd_lai_en_heure_entre_d_c_s_h_0_e_139',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Imagerie2',
        'title' => E::ts('Utilisation du corps :: Imagerie2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_3T_MGH',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 3T MGH'),
        'value' => '7',
        'name' => 'IRM_3T_MGH',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_3T_Neurospin',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 3T Neurospin'),
        'value' => '8',
        'name' => 'IRM_3T_Neurospin',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_3T_Tours_cerveau_frais',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 3T Tours cerveau frais'),
        'value' => '9',
        'name' => 'IRM_3T_Tours_cerveau_frais',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_3T_Tours_MFE',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 3T Tours MFE'),
        'value' => '3',
        'name' => 'IRM_3T_Tours_MFE',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_7T_Neurospin',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 7T Neurospin'),
        'value' => '4',
        'name' => 'IRM_7T_Neurospin',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_11_4_T_Neurospin',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 11.4 T Neurospin'),
        'value' => '6',
        'name' => 'IRM_11_4_T_Neurospin',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_in_vivo_3T',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM in vivo 3T'),
        'value' => '1',
        'name' => 'IRM_in_vivo_3T',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_in_vivo_7T',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM in vivo 7T'),
        'value' => '2',
        'name' => 'IRM_in_vivo_7T',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_Recon_surface_3T',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('Recon surface 3T'),
        'value' => '5',
        'name' => 'Recon_surface_3T',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_3T_Tours_Blockface',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 3T Tours Blockface'),
        'value' => '10',
        'name' => 'IRM 3T Tours Blockface',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Imagerie2_OptionValue_IRM_3T_Tours_tranches',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'label' => E::ts('IRM 3T Tours tranches'),
        'value' => '11',
        'name' => 'IRM 3T Tours tranches',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Imagerie2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Imagerie2',
        'label' => E::ts('Imagerie'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'imagerie2_161',
        'option_group_id.name' => 'Utilisation_du_corps_Imagerie2',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inclusion_en_paraffine2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'title' => E::ts('Utilisation du corps :: Inclusion en paraffine2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inclusion_en_paraffine2_OptionValue_Eau',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'label' => E::ts('Eau'),
        'value' => '1',
        'name' => 'Eau',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inclusion_en_paraffine2_OptionValue_Ethanol',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'label' => E::ts('Ethanol'),
        'value' => '2',
        'name' => 'Ethanol',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inclusion_en_paraffine2_OptionValue_Isopropanol',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'label' => E::ts('Isopropanol'),
        'value' => '6',
        'name' => 'Isopropanol',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inclusion_en_paraffine2_OptionValue_Paraffine_bloc',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'label' => E::ts('Paraffine bloc'),
        'value' => '5',
        'name' => 'Paraffine_bloc',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inclusion_en_paraffine2_OptionValue_Paraffine_immersion',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'label' => E::ts('Paraffine immersion'),
        'value' => '4',
        'name' => 'Paraffine_immersion',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inclusion_en_paraffine2_OptionValue_Xyl_ne',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'label' => E::ts('Xylène'),
        'value' => '3',
        'name' => 'Xyl_ne',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Inclusion_en_paraffine2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Inclusion_en_paraffine2',
        'label' => E::ts('Inclusion en paraffine'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'inclusion_en_paraffine2_162',
        'option_group_id.name' => 'Utilisation_du_corps_Inclusion_en_paraffine2',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Klingler2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Klingler2',
        'title' => E::ts('Utilisation du corps :: Klingler2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Klingler2_OptionValue_Congel_D_congel_',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Klingler2',
        'label' => E::ts('Congelé / Décongelé'),
        'value' => '1',
        'name' => 'Congel_D_congel_',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Klingler2_OptionValue_Leptom_ninges_retir_es',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Klingler2',
        'label' => E::ts('Leptoméninges retirées'),
        'value' => '2',
        'name' => 'Leptom_ninges_retir_es',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Klingler2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Klingler2',
        'label' => E::ts('Klingler'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'klingler2_163',
        'option_group_id.name' => 'Utilisation_du_corps_Klingler2',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Lacalisation',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Lacalisation',
        'label' => E::ts('Localisation'),
        'data_type' => 'EntityReference',
        'html_type' => 'Autocomplete-Select',
        'is_required' => TRUE,
        'help_post' => E::ts('entrer % pour obtenir la liste des localisations.
Pour en ajouter : Pièces Anatomiques > créer localisation pièces'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'localisation_142',
        'filter' => 'action=lookup&group=13',
        'in_selector' => TRUE,
        'fk_entity' => 'Organization',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Complement_location',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Complement_location',
        'label' => E::ts('Complément localisation'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'complement_location_195',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Sortie',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Sortie',
        'label' => E::ts('Date de prêt éventuel'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_de_sortie_143',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Date_de_retour',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Date_de_retour',
        'label' => E::ts('Date de retour'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_de_retour_144',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'title' => E::ts('Utilisation du corps :: Mode élimination (hors corps)2'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2_OptionValue_Non_limin_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'label' => E::ts('Non éliminée'),
        'value' => '5',
        'name' => 'Non_limin_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2_OptionValue_Conservation_illimit_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'label' => E::ts('Conservation illimitée'),
        'value' => '4',
        'name' => 'Conservation_illimit_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2_OptionValue_Cr_mation_comme_pi_ce_anatomiqu',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'label' => E::ts('Crémation / Op funéraires'),
        'value' => '1',
        'name' => 'Cr_mation_comme_pi_ce_anatomiqu',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2_OptionValue_Demander_cr_mation',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'label' => E::ts('Demander crémation'),
        'value' => '7',
        'name' => 'Demander_cr_mation',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2_OptionValue_Cr_mation_demand_e',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'label' => E::ts('Crémation demandée'),
        'value' => '8',
        'name' => 'Cr_mation_demand_e',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2_OptionValue_Destruction_par_la_m_thode_util',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'label' => E::ts('Destruction par la méthode utilisée'),
        'value' => '3',
        'name' => 'Destruction_par_la_m_thode_util',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Mode_limination_hors_corps_2_OptionValue_Manquante',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'label' => E::ts('Manquante'),
        'value' => '6',
        'name' => 'Manquante',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Mode_limination_hors_corps_2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Mode_limination_hors_corps_2',
        'label' => E::ts('Mode élimination'),
        'html_type' => 'Select',
        'default_value' => '5',
        'is_required' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'mode_limination_hors_corps_2_164',
        'option_group_id.name' => 'Utilisation_du_corps_Mode_limination_hors_corps_2',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Date_limination_pi_ce',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Date_limination_pi_ce',
        'label' => E::ts('Date élimination'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_limination_hors_corps__146',
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Remarques',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Remarques',
        'label' => E::ts('Remarques'),
        'data_type' => 'Memo',
        'html_type' => 'TextArea',
        'attributes' => 'rows=4, cols=60',
        'note_columns' => 60,
        'note_rows' => 10,
        'column_name' => 'remarques_147',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Utilisation_du_corps_Inventaires',
        'title' => E::ts('Utilisation du corps :: Inventaires'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires_OptionValue_inventaire_test',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'label' => E::ts('inventaire_test'),
        'value' => '1',
        'name' => 'inventaire_test',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires_OptionValue_CDC_Tours_Inserm_labo_B1A_27_08',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'label' => E::ts('CDC Tours - Inserm labo B1A_27/08/2025_Destrieux'),
        'value' => '3',
        'name' => 'CDC_Tours_Inserm_labo_B1A_27_08',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires_OptionValue_CDC_Tours_Salle_des_cuves_28_08',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'label' => E::ts('CDC Tours - Salle des cuves_28/08/2025_Leveau'),
        'value' => '7',
        'name' => 'CDC_Tours_Salle_des_cuves_28_08',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires_OptionValue_CDC_Tours_Plastination_28_08_20',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'label' => E::ts('CDC Tours - Plastination_28/08/2025_Leveau'),
        'value' => '5',
        'name' => 'CDC_Tours_Plastination_28_08_20',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires_OptionValue_CDC_Tours_Microanatomie_28_08_2',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'label' => E::ts('CDC Tours - Microanatomie_28/08/2025_Leveau'),
        'value' => '6',
        'name' => 'CDC_Tours_Microanatomie_28_08_2',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires_OptionValue_CDC_Tours_Chambre_froide_2_C_28',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'label' => E::ts('CDC Tours - Chambre froide +2°C_28/08/2025_Leveau'),
        'value' => '8',
        'name' => 'CDC_Tours_Chambre_froide_2_C_28',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Utilisation_du_corps_Inventaires_OptionValue_CDC_Tours_Cong_l_Tiroirs_18_C_2',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'label' => E::ts('CDC Tours - Congél Tiroirs -18°C_28/08/2025_Leveau'),
        'value' => '9',
        'name' => 'CDC_Tours_Cong_l_Tiroirs_18_C_2',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Utilisation_du_corps_CustomField_Inventaires',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Utilisation_du_corps',
        'name' => 'Inventaires',
        'label' => E::ts('Inventaires'),
        'html_type' => 'Select',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'inventaires_185',
        'option_group_id.name' => 'Utilisation_du_corps_Inventaires',
        'serialize' => 1,
        'in_selector' => TRUE,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
