<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_Devenir_du_corps',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Devenir_du_corps',
        'title' => E::ts('Devenir du corps'),
        'extends' => 'Individual',
        'extends_entity_column_value' => ['Donateur'],
        'weight' => 9,
        'created_date' => '2022-05-02 18:27:48',
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'cesp_20220502190911',
        'title' => E::ts('CESP'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911_OptionValue_Pas_de_d_rogation',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'cesp_20220502190911',
        'label' => E::ts('Pas de dérogation'),
        'value' => '1',
        'name' => 'Pas_de_d_rogation',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911_OptionValue_Segmentation',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'cesp_20220502190911',
        'label' => E::ts('Segmentation'),
        'value' => '2',
        'name' => 'Segmentation',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911_OptionValue_Restitution_corps_impossible',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'cesp_20220502190911',
        'label' => E::ts('Restitution corps impossible'),
        'value' => '3',
        'name' => 'Restitution_corps_impossible',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911_OptionValue_Restauration_corps_impossible',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'cesp_20220502190911',
        'label' => E::ts('Restauration corps impossible'),
        'value' => '4',
        'name' => 'Restauration_corps_impossible',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911_OptionValue_Conservation_plus_2_ans',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'cesp_20220502190911',
        'label' => E::ts('Conservation 2 ans + 6mois'),
        'value' => '5',
        'name' => 'Conservation_plus_2_ans',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911_OptionValue_Conservation_2_ans_12_mois',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'cesp_20220502190911',
        'label' => E::ts('Conservation 2 ans + 12 mois'),
        'value' => '7',
        'name' => 'Conservation_2_ans_12_mois',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_cesp_20220502190911_OptionValue_Conservation_d_finitive',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'cesp_20220502190911',
        'label' => E::ts('Conservation définitive'),
        'value' => '6',
        'name' => 'Conservation_d_finitive',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_CESP',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'CESP',
        'label' => E::ts('CESP'),
        'html_type' => 'Select',
        'default_value' => '1',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'cesp_61',
        'option_group_id.name' => 'cesp_20220502190911',
        'serialize' => 1,
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_ref_avis_CESP',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'ref_avis_CESP',
        'label' => E::ts('ref avis CESP'),
        'html_type' => 'Text',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'ref_avis_cesp_62',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_D_cision_de_suspension_acc_s_au_corps',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'D_cision_de_suspension_acc_s_au_corps',
        'label' => E::ts('Décision de suspension accès au corps'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '0',
        'help_pre' => E::ts('Décision de suspension ou d’interdiction d’accès au corps en application du dernier alinéa du IV de l’article R. 1261-21'),
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'd_cision_de_suspension_acc_s_au__99',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_effectif_du_corps_20220502191136',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'devenir_effectif_du_corps_20220502191136',
        'title' => E::ts('devenir effectif du corps'),
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_effectif_du_corps_20220502191136_OptionValue_Non_realis_es',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_effectif_du_corps_20220502191136',
        'label' => E::ts('Non realisées'),
        'value' => '5',
        'name' => 'Non realisées',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_effectif_du_corps_20220502191136_OptionValue_Cr_mation_dispersion_par_CDC',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_effectif_du_corps_20220502191136',
        'label' => E::ts('Crémation - dispersion par CDC'),
        'value' => '1',
        'name' => 'Cr_mation_dispersion_par_CDC',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_effectif_du_corps_20220502191136_OptionValue_Restitution_de_cendres',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_effectif_du_corps_20220502191136',
        'label' => E::ts('Restitution de cendres'),
        'value' => '2',
        'name' => 'Restitution_de_cendres',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_effectif_du_corps_20220502191136_OptionValue_Restitution_de_corps',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_effectif_du_corps_20220502191136',
        'label' => E::ts('Restitution de corps'),
        'value' => '3',
        'name' => 'Restitution_de_corps',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_devenir_effectif_du_corps_20220502191136_OptionValue_Conservation_sans_limite',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'devenir_effectif_du_corps_20220502191136',
        'label' => E::ts('Conservation sans limite'),
        'value' => '4',
        'name' => 'Conservation_sans_limite',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_devenir_effectif_du_corps',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'devenir_effectif_du_corps',
        'label' => E::ts('Opération funéraire réalisée'),
        'html_type' => 'Select',
        'default_value' => '5',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'devenir_effectif_du_corps_63',
        'option_group_id.name' => 'devenir_effectif_du_corps_20220502191136',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_Date_de_sortie_d_finitive',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'Date_de_sortie_d_finitive',
        'label' => E::ts('Date de sortie définitive'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_de_sortie_d_finitive_64',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_Date_op_rations_fun_raires',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'Date_op_rations_fun_raires',
        'label' => E::ts('Date opérations funéraires'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_op_rations_fun_raires_100',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_Date_approximative_de_r_alisation_des_op_rations_fun_raires',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'Date_approximative_de_r_alisation_des_op_rations_fun_raires',
        'label' => E::ts('Date approximative de réalisation des opérations funéraires'),
        'data_type' => 'Boolean',
        'html_type' => 'Radio',
        'default_value' => '0',
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_approximative_de_r_alisatio_117',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_Date_de_restitution',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'Date_de_restitution',
        'label' => E::ts('Date de restitution'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'text_length' => 255,
        'date_format' => 'dd/mm/yy',
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date_de_restitution_103',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_Pompes_fun_bres_mandat_es_par_proches',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'Pompes_fun_bres_mandat_es_par_proches',
        'label' => E::ts('Pompes funèbres mandatées par proches'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'pompes_fun_bres_mandat_es_par_pr_106',
        'filter' => 'action=lookup&group=64',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Devenir_du_corps_Souhait_funeraire_personne_ref_rente',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Devenir_du_corps_Souhait_funeraire_personne_ref_rente',
        'title' => E::ts('Devenir du corps :: Souhait funeraire personne reférente'),
        'data_type' => 'Int',
        'is_reserved' => FALSE,
        'option_value_fields' => ['name', 'label', 'description'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_Devenir_du_corps_Souhait_funeraire_personne_ref_rente_OptionValue_R_cup_ration_des_cendres',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Devenir_du_corps_Souhait_funeraire_personne_ref_rente',
        'label' => E::ts('Inconnue'),
        'value' => '1',
        'name' => 'R_cup_ration_des_cendres',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Devenir_du_corps_Souhait_funeraire_personne_ref_rente_OptionValue_Pas_de_r_cup_ration_des_cendres',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Devenir_du_corps_Souhait_funeraire_personne_ref_rente',
        'label' => E::ts('Souhait du donneur'),
        'value' => '2',
        'name' => 'Pas_de_r_cup_ration_des_cendres',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Devenir_du_corps_Souhait_funeraire_personne_ref_rente_OptionValue_R_cup_ration_du_corps',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Devenir_du_corps_Souhait_funeraire_personne_ref_rente',
        'label' => E::ts('Refus de prise en charge'),
        'value' => '3',
        'name' => 'R_cup_ration_du_corps',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Devenir_du_corps_Souhait_funeraire_personne_ref_rente_OptionValue_En_l_absence_de_volont_du_donne',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Devenir_du_corps_Souhait_funeraire_personne_ref_rente',
        'label' => E::ts('En l absence de volonté du donneur : restitution'),
        'value' => '4',
        'name' => 'En_l_absence_de_volont_du_donne',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Devenir_du_corps_CustomField_Souhait_funeraire_personne_ref_rente',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'Devenir_du_corps',
        'name' => 'Souhait_funeraire_personne_ref_rente',
        'label' => E::ts('Souhait funeraire de la PAQPF'),
        'data_type' => 'Int',
        'html_type' => 'Select',
        'default_value' => '1',
        'is_searchable' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'souhait_funeraire_personne_ref_r_108',
        'option_group_id.name' => 'Devenir_du_corps_Souhait_funeraire_personne_ref_rente',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
