<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'Navigation_SearchDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Rechercher'),
        'name' => 'SearchDDC',
        'icon' => 'crm-i fa-search',
        'has_separator' => NULL,
        'weight' => 10,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_afsearchTousContacts',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Tous contacts'),
        'name' => 'afsearchTousContacts',
        'url' => 'civicrm/tous_contacts',
        'icon' => 'crm-i fa-list-alt',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_afsearchDonneursVivants',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Donneurs vivants'),
        'name' => 'afsearchDonneursVivants',
        'url' => 'civicrm/donneurs_vivants',
        'icon' => 'crm-i fa-list-alt',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_afsearchDonneursDCDS',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Donneurs décédés'),
        'name' => 'afsearchDonneursDCDS',
        'url' => 'civicrm/donneurs_DCD',
        'icon' => 'crm-i fa-list-alt',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_afsearchDonneursAnnulS',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Donneurs annulés'),
        'name' => 'afsearchDonneursAnnulS',
        'url' => 'civicrm/donneurs_annules',
        'icon' => 'crm-i fa-list-alt',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_anonymises_purges',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Contacts anonymisés (purgés)'),
        'name' => 'anonymises purges',
        'url' => '[cms.root]/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fsearch#/display/Anonymis_s_par_la_purge/Anonymis_s_par_la_purge',
        'icon' => 'crm-i fa-list-alt',
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
        'has_separator' => 1,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_Adresses_de_donneur_avec_ville_ou_CP_incorrects',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Adresses de donneur avec ville ou CP incorrects'),
        'name' => 'Adresses de donneur avec ville ou CP incorrects',
        'url' => 'civicrm/errCP',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
        'has_separator' => 1,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_Find_Contributions',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Chercher Dons financiers'),
        'name' => 'Find Contributions',
        'url' => 'civicrm/contribute/search?reset=1',
        'permission' => [
          'accéder à CiviContribute',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_Find_Mailings',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Chercher Mailings'),
        'name' => 'Find Mailings',
        'url' => 'civicrm/mailing?reset=1',
        'permission' => [
          'accéder à CiviMail',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_Find_Activities',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Chercher Activités'),
        'name' => 'Find Activities',
        'url' => 'civicrm/activity/search?reset=1',
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
        'has_separator' => 1,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_Advanced_Search',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Recherche avancée'),
        'name' => 'Advanced Search',
        'url' => 'civicrm/contact/search/advanced?reset=1',
        'permission_operator' => 'AND',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_SearchDDC_Navigation_search_kit',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('SearchKit'),
        'name' => 'search_kit',
        'url' => 'civicrm/admin/search',
        'icon' => 'crm-i fa-search-plus',
        'permission' => [
          'administer CiviCRM data',
          'administer search_kit',
        ],
        'permission_operator' => 'OR',
        'parent_id.name' => 'SearchDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
];
