<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'Navigation_ContactsDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Contacts'),
        'name' => 'ContactsDDC',
        'icon' => 'crm-i fa-address-book-o',
        'has_separator' => NULL,
        'weight' => 23,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_New_DonateurDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouveau Donneur'),
        'name' => 'New DonateurDDC',
        'url' => 'civicrm/profile/create/?gid=1&reset=1',
        'permission' => [
          'Ajouter des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Ajouter_proche_donateurDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouveau proche de donneur'),
        'name' => 'Ajouter proche donateurDDC',
        'url' => 'civicrm/profile/create/?gid=20&reset=1',
        'permission' => [
          'Ajouter des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_New_Demandeur_d_informationDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouveau Demandeur d\'information'),
        'name' => 'New Demandeur_d_informationDDC',
        'url' => 'civicrm/profile/create/?gid=17&reset=1',
        'permission' => [
          'Ajouter des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Nouvelle_pi_ce_anat_compar_e',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouvelle pièce anat comparée'),
        'name' => 'Nouvelle pièce anat comparée',
        'url' => 'civicrm/profile/create/?gid=19&reset=1',
        'icon' => 'crm-i fa-cow',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
        'has_separator' => 2,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_MairiesDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Mairies'),
        'name' => 'MairiesDDC',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
        'has_separator' => 2,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_MairiesDDC_Navigation_afsearchMairies',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Rechercher mairies'),
        'name' => 'afsearchMairies',
        'url' => 'civicrm/mairies',
        'icon' => 'crm-i fa-list-alt',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'MairiesDDC',
        'has_separator' => NULL,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_MairiesDDC_Navigation_New_Mairies',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouvelle Mairie'),
        'name' => 'New Mairies',
        'url' => 'civicrm/profile/create/?gid=23&reset=1',
        'permission' => [
          'Ajouter des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'MairiesDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_MairiesDDC_Navigation_Annuaire_officiel_des_mairies',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Annuaire officiel des mairies'),
        'name' => 'Annuaire officiel des mairies',
        'url' => 'https://lannuaire.service-public.fr/navigation/mairie',
        'icon' => 'crm-i fa-university',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'MairiesDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Centres_de_don_du_corpsDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Centres de don du corps'),
        'name' => 'Centres de don du corpsDDC',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Centres_de_don_du_corpsDDC_Navigation_New_CDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouveau Centre de don de corps'),
        'name' => 'New CDC',
        'url' => 'civicrm/profile/create/?gid=15&reset=1',
        'permission' => [
          'Ajouter des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'Centres de don du corpsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Centres_de_don_du_corpsDDC_Navigation_New_Personnel',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouveau personnel de CDC'),
        'name' => 'New Personnel',
        'url' => 'civicrm/profile/create/?gid=25&reset=1',
        'permission' => [
          'Ajouter des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'Centres de don du corpsDDC',
        'has_separator' => 1,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Centres_de_don_du_corpsDDC_Navigation_afsearchCentresDAccueilDesCorps',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Centres d\'accueil des corps'),
        'name' => 'afsearchCentresDAccueilDesCorps',
        'url' => 'civicrm/CDC',
        'icon' => 'crm-i fa-list-alt',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'Centres de don du corpsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Pompes_funebresDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Pompes funèbres'),
        'name' => 'Pompes funebresDDC',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
        'has_separator' => 1,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Pompes_funebresDDC_Navigation_New_Pompes',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouvelle entreprise de Pompes Funèbres'),
        'name' => 'New Pompes',
        'url' => 'civicrm/profile/create/?gid=21&reset=1',
        'permission' => [
          'Ajouter des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'Pompes funebresDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Pompes_funebresDDC_Navigation_afsearchRechercherPompesFunBres',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Recherche pompes funèbres'),
        'name' => 'afsearchRechercherPompesFunBres',
        'url' => 'civicrm/pompes',
        'icon' => 'crm-i fa-list-alt',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'Pompes funebresDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_New_Activity',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouvelle activitéDDC'),
        'name' => 'New Activity',
        'url' => 'civicrm/activity?reset=1&action=add&context=standalone',
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_Find_and_Merge_Duplicate_ContactsDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Rechercher les doublons'),
        'name' => 'Find and Merge Duplicate ContactsDDC',
        'url' => 'civicrm/contact/deduperules?reset=1',
        'permission' => [
          'gérer les règles de dédoublonnage',
          'merge duplicate contacts',
        ],
        'permission_operator' => 'OR',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_ImportsDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Imports'),
        'name' => 'ImportsDDC',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
        'has_separator' => 1,
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_ImportsDDC_Navigation_Import_ContactsDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Importer des Contacts'),
        'name' => 'Import ContactsDDC',
        'url' => 'civicrm/import/contact?reset=1',
        'permission' => [
          'Importer des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ImportsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_ImportsDDC_Navigation_Import_MultiValued_CustomDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Importer (valeurs multiples)'),
        'name' => 'Import MultiValued CustomDDC',
        'url' => 'civicrm/import/custom?reset=1',
        'permission' => [
          'Importer des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ImportsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_ImportsDDC_Navigation_Import_ActivitiesDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Importer des Activités'),
        'name' => 'Import ActivitiesDDC',
        'url' => 'civicrm/import/activity?reset=1',
        'permission' => [
          'Importer des contacts',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ImportsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_GroupesDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Groupes'),
        'name' => 'GroupesDDC',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_GroupesDDC_Navigation_Manage_GroupsDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Gestion des groupes'),
        'name' => 'Manage GroupsDDC',
        'url' => 'civicrm/group?reset=1',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'GroupesDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_GroupesDDC_Navigation_New_GroupDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouveau Groupe'),
        'name' => 'New GroupDDC',
        'url' => 'civicrm/group/add?reset=1',
        'permission' => [
          'Modifier les groupes',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'GroupesDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_TagsDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Tags/Étiquettes'),
        'name' => 'TagsDDC',
        'permission' => ['access CiviCRM'],
        'permission_operator' => 'AND',
        'parent_id.name' => 'ContactsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_TagsDDC_Navigation_Manage_Tags_Categories_DDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Gestion des Tags'),
        'name' => 'Manage Tags (Categories)DDC',
        'url' => 'civicrm/tag?reset=1',
        'permission' => [
          'gérer les tags/étiquettes',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'TagsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
  [
    'name' => 'Navigation_ContactsDDC_Navigation_TagsDDC_Navigation_New_TagDDC',
    'entity' => 'Navigation',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'label' => E::ts('Nouveau Tag'),
        'name' => 'New TagDDC',
        'url' => 'civicrm/tag?reset=1&action=add',
        'permission' => [
          'gérer les tags/étiquettes',
        ],
        'permission_operator' => 'AND',
        'parent_id.name' => 'TagsDDC',
      ],
      'match' => ['name', 'domain_id'],
    ],
  ],
];
