<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'OptionGroup_activity_type',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'activity_type',
        'title' => E::ts('Type d\'activité'),
        'description' => E::ts('Les activités historisent les interactions avec les contacts. Certains types d\'activités sont réservés à une utilisation par des processus automatisés, d\'autres peuvent être configurés librement.'),
        'data_type' => 'Integer',
        'option_value_fields' => ['name', 'label', 'description', 'icon'],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Meeting',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Réunion'),
        'value' => '1',
        'name' => 'Meeting',
        'is_default' => NULL,
        'is_reserved' => TRUE,
        'icon' => 'fa-slideshare',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Phone_Call',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Appel téléphonique'),
        'value' => '2',
        'name' => 'Phone Call',
        'is_default' => NULL,
        'is_reserved' => TRUE,
        'icon' => 'fa-phone',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Email',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Courriel'),
        'value' => '3',
        'name' => 'Email',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Courriel envoyé.'),
        'is_reserved' => TRUE,
        'icon' => 'fa-envelope-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_SMS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('SMS sortant'),
        'value' => '4',
        'name' => 'SMS',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Texto (SMS) envoyé.'),
        'is_reserved' => TRUE,
        'icon' => 'fa-mobile',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Event_Registration',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Inscription à événement'),
        'value' => '5',
        'name' => 'Event Registration',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Inscription à événement en ligne et hors ligne.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviEvent',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Contribution',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Don financier'),
        'value' => '6',
        'name' => 'Contribution',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Don financier en ligne et hors ligne.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Membership_Signup',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Adhésion'),
        'value' => '7',
        'name' => 'Membership Signup',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Adhésion en ligne et hors ligne.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviMember',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Membership_Renewal',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Renouvellement d\'adhésion'),
        'value' => '8',
        'name' => 'Membership Renewal',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Renouvellement d\'adhésion en ligne et hors ligne.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviMember',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Tell_a_Friend',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Recommander à un ami'),
        'value' => '9',
        'name' => 'Tell a Friend',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Envoyer des informations sur une campagne de contribution ou un événement à un ami.'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Pledge_Acknowledgment',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Accusé de réception d\'engagement de don'),
        'value' => '10',
        'name' => 'Pledge Acknowledgment',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Envoyer accusé de réception d\'engagement de don.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviPledge',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Pledge_Reminder',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Rappel d\'engagement de don'),
        'value' => '11',
        'name' => 'Pledge Reminder',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Envoyer un rappel d\'engagement de don.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviPledge',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Inbound_Email',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Courriel entrant'),
        'value' => '12',
        'name' => 'Inbound Email',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Courriel entrant.'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Open_Case',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Dossier ouvert'),
        'value' => '13',
        'name' => 'Open Case',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-folder-open-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Follow_up',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Suivi'),
        'value' => '14',
        'name' => 'Follow up',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-share-square-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Case_Type',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Changer le type du dossier'),
        'value' => '15',
        'name' => 'Change Case Type',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-random',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Case_Status',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Changer le statut du dossier'),
        'value' => '16',
        'name' => 'Change Case Status',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-pencil-square-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Membership_Renewal_Reminder',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Rappel de renouvellement d\'adhésion'),
        'value' => '17',
        'name' => 'Membership Renewal Reminder',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Rappel de renouvellement d\'adhésion hors ligne.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviMember',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Case_Start_Date',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Changer la date d\'ouverture du dossier'),
        'value' => '18',
        'name' => 'Change Case Start Date',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-calendar',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Bulk_Email',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Envoi massif'),
        'value' => '19',
        'name' => 'Bulk Email',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Mailing envoyé.'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Assign_Case_Role',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Assigner un rôle au dossier'),
        'value' => '20',
        'name' => 'Assign Case Role',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-user-plus',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Remove_Case_Role',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Enlever un rôle du dossier'),
        'value' => '21',
        'name' => 'Remove Case Role',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-user-times',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Print_PDF_Letter',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Imprimer/fusionner le document'),
        'value' => '22',
        'name' => 'Print PDF Letter',
        'is_default' => NULL,
        'description' => E::ts('Exporter les lettres et autres documents imprimables.'),
        'is_reserved' => TRUE,
        'icon' => 'fa-file-pdf-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Merge_Case',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Fusionner des dossiers'),
        'value' => '23',
        'name' => 'Merge Case',
        'is_default' => NULL,
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-compress',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Reassigned_Case',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Dossier réassigné'),
        'value' => '24',
        'name' => 'Reassigned Case',
        'is_default' => NULL,
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-user-circle-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Link_Cases',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Lier des dossiers'),
        'value' => '25',
        'name' => 'Link Cases',
        'is_default' => NULL,
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-link',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Case_Tags',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Changer des étiquettes de dossier'),
        'value' => '26',
        'name' => 'Change Case Tags',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-tags',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Add_Client_To_Case',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Ajouter un client au dossier'),
        'value' => '27',
        'name' => 'Add Client To Case',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-users',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Survey',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Questionnaire'),
        'value' => '28',
        'name' => 'Survey',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCampaign',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Canvass',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Démarcher'),
        'value' => '29',
        'name' => 'Canvass',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCampaign',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_PhoneBank',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Banque par téléphone'),
        'value' => '30',
        'name' => 'PhoneBank',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCampaign',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_WalkList',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Liste itinéraire'),
        'value' => '31',
        'name' => 'WalkList',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCampaign',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Petition',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Signature de pétition'),
        'value' => '32',
        'name' => 'Petition',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCampaign',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Custom_Data',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Changer les données personnalisées'),
        'value' => '33',
        'name' => 'Change Custom Data',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-table',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Mass_SMS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Envoi groupé de SMS '),
        'value' => '34',
        'name' => 'Mass SMS',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Envoi groupé de SMS '),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Membership_Status',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Modifier le statut d\'adhésion'),
        'value' => '35',
        'name' => 'Change Membership Status',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Changer le statut d\'adhésion.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviMember',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Membership_Type',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Changer le type d\'adhésion'),
        'value' => '36',
        'name' => 'Change Membership Type',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Changer le type d\'adhésion.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviMember',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Cancel_Recurring_Contribution',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Supprimer la contribution périodique'),
        'value' => '37',
        'name' => 'Cancel Recurring Contribution',
        'filter' => 1,
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Update_Recurring_Contribution_Billing_Details',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Mettre à jour les données de facturation de la contribution périodique'),
        'value' => '38',
        'name' => 'Update Recurring Contribution Billing Details',
        'filter' => 1,
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Update_Recurring_Contribution',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Mettre à jour la contribution périodique'),
        'value' => '39',
        'name' => 'Update Recurring Contribution',
        'filter' => 1,
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Reminder_Sent',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Rappel Envoyé'),
        'value' => '40',
        'name' => 'Reminder Sent',
        'filter' => 1,
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Export_Accounting_Batch',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Export comptabilité par lot'),
        'value' => '41',
        'name' => 'Export Accounting Batch',
        'filter' => 1,
        'description' => E::ts('Exporter la comptabilité par lot'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_SMS_delivery',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Envoi SMS'),
        'value' => '44',
        'name' => 'SMS delivery',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Envoi SMS'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Inbound_SMS',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('SMS entrant'),
        'value' => '45',
        'name' => 'Inbound SMS',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('SMS entrant'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Payment',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Paiement'),
        'value' => '46',
        'name' => 'Payment',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Paiement supplémentaire enregistré pour un événement ou des frais d\'adhésion.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Refund',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Remboursement'),
        'value' => '47',
        'name' => 'Refund',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Remboursement enregistré pour un événement ou des frais d\'adhésion.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Registration',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Modifier l\'inscription'),
        'value' => '48',
        'name' => 'Change Registration',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Modifications apportées à une inscription existante à un événement.'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviEvent',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Downloaded_Invoice',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Facture téléchargée'),
        'value' => '49',
        'name' => 'Downloaded Invoice',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Facture téléchargée.'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Emailed_Invoice',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Facture envoyée par courrier électronique'),
        'value' => '50',
        'name' => 'Emailed Invoice',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Facture envoyée par courrier électronique.'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Contact_Merged',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Contact fusionné'),
        'value' => '51',
        'name' => 'Contact Merged',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Contact fusionné'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Contact_Deleted_by_Merge',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Contact supprimé par fusion'),
        'value' => '52',
        'name' => 'Contact Deleted by Merge',
        'filter' => 1,
        'is_default' => NULL,
        'description' => E::ts('Le contact a été fusionné dans un autre contact'),
        'is_reserved' => TRUE,
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Change_Case_Subject',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Modifier le sujet de Dossier'),
        'value' => '53',
        'name' => 'Change Case Subject',
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-pencil-square-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Failed_Payment',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Paiement échoué'),
        'value' => '54',
        'name' => 'Failed Payment',
        'filter' => 1,
        'description' => E::ts('Paiement échoué'),
        'is_reserved' => TRUE,
        'component_id:name' => 'CiviContribute',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Case_Client_Removed',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Le client du dossier a été retiré du dossier'),
        'value' => '55',
        'name' => 'Case Client Removed',
        'description' => E::ts('Le client du dossier a été retiré d\'un dossier'),
        'component_id:name' => 'CiviCase',
        'icon' => 'fa-trash',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Document_ajout_au_dossier',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Document ajouté au dossier'),
        'value' => '56',
        'name' => 'Document ajouté au dossier',
        'icon' => 'fa-file-word-o',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Modification_des_coordonn_es',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Modification des coordonnées'),
        'value' => '57',
        'name' => 'Modification des coordonnées',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Retrait_effets_personnels',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Retrait effets personnels'),
        'value' => '58',
        'name' => 'Retrait effets personnels',
        'description' => E::ts('<p>Retrait d\'effet personnel de valeur</p>'),
        'icon' => 'fa-diamond',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Retrait_de_pace_maker',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Retrait de pace maker'),
        'value' => '59',
        'name' => 'Retrait de pace maker',
        'icon' => 'fa-heart-circle-bolt',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Inventaire',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Inventaire'),
        'value' => '60',
        'name' => 'Inventaire',
        'description' => E::ts('<p>Inventaire des pièces et corps d\'un lieu de conservation,<strong> à créer depuis la fiche du lieu de conservation</strong>.</p>

<p><strong>Les numéros de pièces (codes-barres) doivent être saisis dans le champ Détail</strong>.</p>

<p>A la validation un rapport remplace la liste des pièces dans le champ détail :&nbsp;</p>

<p>- Pièces bien localisées</p>

<p>- Pièces inscrites dans la base comme détruites, manquantes ou crématisées et présentes dans l\'inventaire : leur statut est mis à Non éliminé et elles sont relocalisées</p>

<p>- Pièces absentes de la base : à créer manuellement</p>

<p>- Pièces inscrites dans la base dans une autre pièce : relocalisées</p>'),
        'icon' => 'fa-list-check',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_Suppression_d_une_pi_ces',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Suppression d\'un lot de pièces'),
        'value' => '61',
        'name' => 'Suppression d\'une pièces',
        'description' => E::ts('<p>Permet la suppression des pièces par lot.&nbsp;</p>

<p>Pour les corps : passer par le tableau de bord des corps présents et demander la crémation.</p>'),
        'icon' => 'fa-trash',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_D_placer_un_lot_de_pi_ces_corps',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Déplacer un lot de pièces/corps'),
        'value' => '62',
        'name' => 'Déplacer un lot de pièces/corps',
        'description' => E::ts('<p>Déplace vers ce local un lot de pièces ou de corps dont les codes-barres sont saisis dans le champ <em>Détails</em> de l\'activité.</p>'),
        'icon' => 'fa-arrow-right-arrow-left',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_activity_type_OptionValue_event_message_sent',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'activity_type',
        'label' => E::ts('Event Message sent'),
        'value' => '63',
        'name' => 'event_message_sent',
      ],
      'match' => [
        'option_group_id',
        'name',
        'value',
      ],
    ],
  ],
];
