<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Toutes_pi_ces_corps',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Toutes_pi_ces_corps',
        'label' => E::ts('Tous codes barres'),
        'api_entity' => 'Custom_Utilisation_du_corps',
        'api_params' => [
          'version' => 4,
          'select' => [
            'entity_id.display_name',
            'N_de_pi_ce_ou_de_corps',
            'Custom_Utilisation_du_corps_Contact_entity_id_01.Prise_en_charge_au_d_c_s.N_de_d_c_s',
            'type_de_pi_ce:label',
            'Type_de_poi_ce_3:label',
            'Utilisation2:label',
            'Protocole_de_recherche_ex_vivo2:label',
            'Compl_ment',
            'Lacalisation.display_name',
            'Sortie',
            'Mode_limination_hors_corps_2:label',
            'D_lai_en_heure_entre_d_c_s_h_0_et_injection',
            'id',
          ],
          'orderBy' => [],
          'where' => [
            [
              'Type_de_poi_ce_3:name',
              'IS NOT EMPTY',
            ],
          ],
          'groupBy' => [],
          'join' => [
            [
              'Contact AS Custom_Utilisation_du_corps_Contact_entity_id_01',
              'LEFT',
              [
                'entity_id',
                '=',
                'Custom_Utilisation_du_corps_Contact_entity_id_01.id',
              ],
            ],
          ],
          'having' => [],
        ],
        'description' => E::ts('Liste toutes les codes barres'),
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Toutes_pi_ces_corps_SearchDisplay_Toutes_pi_ces_corps_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Toutes_pi_ces_corps_Table_1',
        'label' => E::ts('Toutes pièces'),
        'saved_search_id.name' => 'Toutes_pi_ces_corps',
        'type' => 'table',
        'settings' => [
          'description' => E::ts('Liste toutes les pièces anatomiques prélevées'),
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'entity_id.display_name',
              'dataType' => 'String',
              'label' => E::ts('Nom'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'N_de_pi_ce_ou_de_corps',
              'dataType' => 'String',
              'label' => E::ts('Code barres'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Custom_Utilisation_du_corps_Contact_entity_id_01.Prise_en_charge_au_d_c_s.N_de_d_c_s',
              'dataType' => 'String',
              'label' => E::ts('N° de décès'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Custom_Utilisation_du_corps_Contact_entity_id_01',
                'target' => '_blank',
              ],
              'title' => E::ts('Voir Utilisation du corps Contact'),
            ],
            [
              'type' => 'field',
              'key' => 'Type_de_poi_ce_3:label',
              'dataType' => 'String',
              'label' => E::ts('Type de pièce'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Utilisation2:label',
              'dataType' => 'String',
              'label' => E::ts('Utilisation'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Protocole_de_recherche_ex_vivo2:label',
              'dataType' => 'String',
              'label' => E::ts('Protocole de recherche'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Compl_ment',
              'dataType' => 'String',
              'label' => E::ts('Complément ou identifiant'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'D_lai_en_heure_entre_d_c_s_h_0_et_injection',
              'dataType' => 'Integer',
              'label' => E::ts('Délai injection (h)'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Lacalisation.display_name',
              'dataType' => 'String',
              'label' => E::ts('Localisation'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Sortie',
              'dataType' => 'Date',
              'label' => E::ts('Date de sortie'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Mode_limination_hors_corps_2:label',
              'dataType' => 'String',
              'label' => E::ts('Mode élimination'),
              'sortable' => TRUE,
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'headerCount' => TRUE,
          'actions_display_mode' => 'menu',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
