<?php
use CRM_DonCorps_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Tokens_for_contact',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Tokens_for_contact',
        'label' => E::ts('Tokens de contact'),
        'api_entity' => 'Contact',
        'api_params' => [
          'version' => 4,
          'select' => [
            'Promesse_de_don.N_de_don',
            'deceased_date',
            'Promesse_de_don.Centre_de_don:label',
            'Promesse_de_don.Date_du_don',
            'Compl_m_nt_tat_civil.Ville_de_naissance',
            'Promesse_de_don.Devenir_souhait_:label',
            'Promesse_de_don.Pr_venir_personne_r_f_rence_de_la_c_r_monie:label',
            'Promesse_de_don.Souhait_lecture_nom:label',
            'Promesse_de_don.Souhiat_affichage_st_le:label',
            'Promesse_de_don.Refus_personne_referente',
            'id',
            'Annulation.Date_d_annulation',
            'Annulation.N_annulation',
            'Prise_en_charge_au_d_c_s.Ville_de_d_c_s',
            'Devenir_du_corps.Date_de_sortie_d_finitive',
            'Devenir_du_corps.Date_op_rations_fun_raires',
            'Prise_en_charge_au_d_c_s.N_de_d_c_s',
            'Devenir_du_corps.Souhait_funeraire_personne_ref_rente:label',
            'champs_caches.piece_prinicpale',
            'postal_greeting_id:label',
            'Demandeur_information.Date_d_envoi_d_informations',
            'GROUP_CONCAT(DISTINCT Contact_Custom_Protocoles_in_vivo_entity_id_01.Intitul_du_protocole:label) AS GROUP_CONCAT_Contact_Custom_Protocoles_in_vivo_entity_id_01_Intitul_du_protocole_label',
            'CONCAT_WS("/", last_name, nick_name) AS CONCAT_WS_last_name_nick_name',
            'id',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => ['id'],
          'join' => [
            [
              'Custom_Protocoles_in_vivo AS Contact_Custom_Protocoles_in_vivo_entity_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Contact_Custom_Protocoles_in_vivo_entity_id_01.entity_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Tokens_for_contact_SearchDisplay_Tokens_for_contact_Champs_de_fusion_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Tokens_for_contact_Champs_de_fusion_1',
        'label' => E::ts('Tokens for contact Champs de fusion 1'),
        'saved_search_id.name' => 'Tokens_for_contact',
        'type' => 'tokens',
        'settings' => [
          'columns' => [
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.N_de_don',
              'dataType' => 'String',
              'label' => E::ts('NumDon'),
              'rewrite' => '[Promesse_de_don.N_de_don]',
            ],
            [
              'type' => 'field',
              'key' => 'deceased_date',
              'dataType' => 'Date',
              'label' => E::ts('DateDeces'),
              'rewrite' => '[deceased_date]',
            ],
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.Centre_de_don:label',
              'dataType' => 'Integer',
              'label' => E::ts('CentreDon'),
              'rewrite' => '[Promesse_de_don.Centre_de_don:label]',
            ],
            [
              'type' => 'field',
              'key' => 'Compl_m_nt_tat_civil.Ville_de_naissance',
              'dataType' => 'String',
              'label' => E::ts('VilleNaiss'),
              'rewrite' => '[Compl_m_nt_tat_civil.Ville_de_naissance]',
            ],
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.Devenir_souhait_:label',
              'dataType' => 'Integer',
              'label' => E::ts('SouhaitsFun'),
              'rewrite' => '[Promesse_de_don.Devenir_souhait_:label]',
            ],
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.Pr_venir_personne_r_f_rence_de_la_c_r_monie:label',
              'dataType' => 'Integer',
              'label' => E::ts('PrevenirRefCerem'),
              'rewrite' => '[Promesse_de_don.Pr_venir_personne_r_f_rence_de_la_c_r_monie:label]',
            ],
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.Souhait_lecture_nom:label',
              'dataType' => 'Integer',
              'label' => E::ts('LectureNom'),
              'rewrite' => '[Promesse_de_don.Souhait_lecture_nom:label]',
            ],
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.Souhiat_affichage_st_le:label',
              'dataType' => 'Integer',
              'label' => E::ts('AffichageStele'),
              'rewrite' => '[Promesse_de_don.Souhiat_affichage_st_le:label]',
            ],
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.Refus_personne_referente',
              'dataType' => 'Boolean',
              'label' => E::ts('RefusReferent'),
              'rewrite' => '[Promesse_de_don.Refus_personne_referente]',
            ],
            [
              'type' => 'field',
              'key' => 'Promesse_de_don.Date_du_don',
              'dataType' => 'Date',
              'label' => E::ts('DateDon'),
              'rewrite' => '[Promesse_de_don.Date_du_don]',
            ],
            [
              'type' => 'field',
              'key' => 'Annulation.Date_d_annulation',
              'dataType' => 'Date',
              'label' => E::ts('AnnulationDate'),
              'rewrite' => '[Annulation.Date_d_annulation][CURDATE()]',
            ],
            [
              'type' => 'field',
              'key' => 'Annulation.N_annulation',
              'dataType' => 'String',
              'label' => E::ts('AnnulationNum'),
            ],
            [
              'type' => 'field',
              'key' => 'Prise_en_charge_au_d_c_s.Ville_de_d_c_s',
              'dataType' => 'String',
              'label' => E::ts('VilleDC'),
            ],
            [
              'type' => 'field',
              'key' => 'Devenir_du_corps.Date_de_sortie_d_finitive',
              'dataType' => 'Date',
              'label' => E::ts('DateSortieDefinitive'),
              'rewrite' => '[Devenir_du_corps.Date_de_sortie_d_finitive][CURDATE()]',
            ],
            [
              'type' => 'field',
              'key' => 'Devenir_du_corps.Date_op_rations_fun_raires',
              'dataType' => 'Date',
              'label' => E::ts('DateOpFun'),
              'rewrite' => '[Devenir_du_corps.Date_op_rations_fun_raires][CURDATE()]',
            ],
            [
              'type' => 'field',
              'key' => 'Prise_en_charge_au_d_c_s.N_de_d_c_s',
              'dataType' => 'String',
              'label' => E::ts('NumDC'),
            ],
            [
              'type' => 'field',
              'key' => 'Devenir_du_corps.Souhait_funeraire_personne_ref_rente:label',
              'dataType' => 'Integer',
              'label' => E::ts('SouhaitFunPAQPF'),
            ],
            [
              'type' => 'field',
              'key' => 'champs_caches.piece_prinicpale',
              'dataType' => 'String',
              'label' => E::ts('NumPiecePrincipale'),
            ],
            [
              'type' => 'field',
              'key' => 'postal_greeting_id:label',
              'label' => E::ts('Salutation_ecrite'),
              'rewrite' => '',
            ],
            [
              'type' => 'field',
              'key' => 'Demandeur_information.Date_d_envoi_d_informations',
              'label' => E::ts('date_dde_infos'),
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Contact_Custom_Protocoles_in_vivo_entity_id_01_Intitul_du_protocole_label',
              'label' => E::ts('prot_invivo'),
            ],
            [
              'type' => 'field',
              'key' => 'CONCAT_WS_last_name_nick_name',
              'label' => E::ts('nom_patro-usage'),
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
